<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <title>泡中机盟</title>
    </div>
    <p class="weui-footer__links">
        <a href="web.html" class="weui-footer__link">进如网站</a>
</div>
	<p class="weui-footer__links">
        <a href="https://gitee.com/windows-17/linspirer" class="weui-footer__link">下载站</a>
    </p>
    <p class="weui-footer__text">Copyright www.gitee.com</p>
</div>
    </div>
</div>
    <script type="text/javascript">
        $(function(){
            $('.weui-navbar__item').on('click', function () {
                $(this).addClass('weui-bar__item_on').siblings('.weui-bar__item_on').removeClass('weui-bar__item_on');

                $($(this).attr("rel")).addClass("active").siblings(".active").removeClass("active");
            });
        });
    </script>
</body>
</html>

