/*
 * 
 * @(#)zh-CN.js
 * Author: Zachary.Ma
 * Date: 30 Apr 2015
 * Discription:
 *
 */


Lang = {
    msg_dialog_title: "****",
    msg_system_error: "系统内部错误，请重试或联系**员",
    msg_file_upload_complete: "文件上传完毕",
    msg_file_upload_error: "文件上传失败，请重试或联系管理员。",
    msg_process_package_error: "应用包解析失败，请重试或联系管理员。",
    msg_command_push_success: "命令已经成功发送",
    msg_command_push_error: "命令发送失败，请重试或联系管理员",
    msg_command_push_fail: "推送失败！",
    msg_command_push_fail_device: "推送失败的设备如下：\n ",
    msg_command_no_token: "没有token(无token设备可通过开关wifi主动获取推送命令), 无法推送的设备如下：\n ",
    msg_workspace_success:"用户合规成功",
    msg_workspace_fail:"用户合规失败,请重试或联系管理员",
    msg_illegal_package : '非法资源上传，请上传后缀名为apk/ipa的应用安装包',
    msg_unupload_package : '未上传应用，请重新上传。',
    msg_command_not_loggin: "登录超时或未登录",
    msg_command_device_no_token: "该设备缺少推送token,请稍后再试或者联系管理员。",
    msg_comfirm_delete:"确定删除",
    msg_sure:"吗?",
    msg_app_not_match:"应用种类与上传的应用安装包类型不符，请修改应用种类或者重新上传正确的安装包",
    msg_press_appname:"请输入应用名称",
    msg_press_devicename:"请输入设备号",
    msg_check_device:"请勾选至少一个设备",
    msg_check_tactics:"请至少选择一个策略",
    msg_restore_factory_setting:"恢复出厂设置",
    msg_restore_remind:"恢复出厂设置，将清除设备中的所有数据，确定对所选设备进行此操作吗？",
    msg_unlock_workspace:"设备合规处理",
    msg_unlock_workspace_remind:"设备合规处理，将解除设备限制，确定对所选设备进行操作吗？",
    msg_message_length:"消息的长度超过256字符。",
    msg_title_length:"消息标题长度超过32字符",
    msg_effective_message:"请输入有效的消息标题和内容.",
    msg_delete_fail:"删除失败",
    msg_comfirm_delete_wifi:"您确定要删除wifi:",
    msg_reset_the_audit:"确定重置审核状态吗?",
    msg_pass_the_audit:"确定通过审核吗?",
    msg_not_pass_audit:"确定不通过审核吗?",
    msg_comfirm_audit:"确定审核",
    msg_illegal_urlpath :'请填写正确的url地址',
    msg_not_lock_screen : '设备未锁定',
    msg_check_url:"请至少选择一个网址白名单",
    status_0:"禁用",
    status_1:"启用",
    msg_unbind_device_confirm:"解除设备绑定，将解除该用户和设备的绑定关系，确定对所选用户设备进行此操作吗？",
    user_not_login_or_login_timeout:"您还没有登陆或者登陆超时，请重新登陆",
    current_page_has_expired:"当前页面已经过期，请刷新页面",
    please_selected_one_user:"请至少选择一个用户",
    please_selected_one_class:"请至少选择一个班级",
    release_control_confirm:"解除管控目前只支持部分设备, 你确定要解除管控吗? ",
    release_control_danger: "解除管控后设备将处于普通模式，请谨慎操作",
    please_select_one_group:"整班解除管控时必须选择一个班级",
    please_select_one_group_to_send_message:"整班发送消息时必须选择一个班级",
    please_select_one_group_to_delete_user:"整班删除用户时必须选择一个班级",
    one_class_release_control_confirm:" 你确定要解除整个班级的用户管控吗",
    one_class_to_delete_user_confirm:" 你确定要删除整个班级的用户吗",
    release_one_class_control_tip:"解除整个班级的管控非常危险，解除管控后设备将处于普通模式，请谨慎操作.",
    release_one_class_to_delete_user_control_tip:"删除整个班级的用户非常危险，删除后整个班级的用户都不可使用了，请谨慎操作.",
    application_duration:"应用使用时长(秒)",
    launch_count:"应用启动次数",
    app_usage_statics:"应用使用统计",
    device_use_statics:"设备使用统计",
    device_use_time:"设备使用时长",
    app_use_time_percent:"应用使用时长比例",
    select_all: "全选",
    brand: '厂商',
    brand_1: "华为",
    brand_2: "联想",
    brand_3: "海信",
    brand_4: "华瑞安",
    brand_1000: "其他",
    search_key_has_slashes: "搜索关键字中不能包含'/' , '\\' 和 '..'",
    dynamic_pwd: '动态密码',


    Sun: '日',
    Mon: '一',
    Tue: '二',
    Wed: '三',
    Thu: '四',
    Fri: '五',
    Sat: '六',

    effect: "生效",
    cancel: "取消",
    cancel_select_time: "取消选择时间",
    confirm_select_time: "确定选择时间",
    status_init: "状态:已初始化",
    status_invalid: "状态:未生效",
    status_valid: "状态:已生效",
    valid: "有效",
    invalid: "无效",
    each_td_means: "每个格子为30分钟",
    positive_election: "正选",
    reverse_election: "反选",
    data_format_incorrect: "数据格式不正确",

    request_error: "请求失败，请检查网络或者联系系统管理员后重试～",

    confirm: '确 认',
    message: '消 息',
    success: '成 功',
    warning: '警 告',
    error: '错 误',
    btn_cancel: "取 消",
    submit: "确 定",
    close: "关 闭",
    get_password: "获取密码",
    one_class_send_message_confirm:" 你确定要给整个班级的用户发送消息吗?",

    inputAppName: "请输入应用名",
    applicationList: "应用列表",
    authorizedApplication: "授权应用",

    hasNoPermission: "您没有权限,系统已将你注销登陆,请重新登陆!",
    free_control_confirm:"开启家长管控后,设备允许家长自行管理,你确定要开启家长管控吗? ",
    week: "周",
    invalidRequestParameter: "请求参数无效!",
    please_enter_valid_phone_number : "请输入有效的手机号码！",
    reacquire_pre: "重新获取(",
    reacquire_suffix: ")",
    getVerificationCode: "获取验证码",
    phoneTip: '若填写，请确认手机号可用，便于后续使用短信验证码登录',
    batchSetLegalDeviceConfirm:"您确定对所选用户设备进行合规处理操作吗？",
    hasIllegalDevice:"您选择的设备中包含违规设备，请先将设备合规处理!",
};

